### ISSUE TITLE
Добавить релиз 1.0

### ISSUE THREAD

**Issue by vertx-one** [eugenezadorin/bitrix-psalm-plugin#1]
Со старта проекта по умолчанию minimum-stability: stable и это оптимально для большинства проектов. Так как у плагина нет ни одного релиза (тега), то получается стабильной версии нет и composer не дает поставить этот плагин без правок minimum-stability в composer.json
 
Появление релиза увеличит сообщество вокруг плагина

Готов помочь в поддержке плагина.

**Comment by eugenezadorin** [comment]
Добавил релиз v0.0.2 и зафиксировал стабильную версию самого Psalm. Сейчас это `^4.19`.

Проверил, плагин ставится в проект с `minimum-stability: stable`

**Comment by vertx-one** [comment]
Благодарю!
